# NCEI Weather Features

In [3]:
import pandas as pd
import numpy as np

raw_data = "../data/raw_files/BTV_NCEI_weather_data.csv"
output_csv = "../data/unified_csvs/ncei_weather_avg.csv"

## Load CSV

In [17]:
df = pd.read_csv(raw_data)

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 0)

df["DATE"] = pd.to_datetime(df["DATE"])
df = df.set_index("DATE")
df.head()

,STATION,NAME,AWND,FMTM,PGTM,PRCP,PSUN,SNOW,SNWD,TAVG,TMAX,TMIN,TSUN,WDF2,WDF5,WESD,WSF2,WSF5,WT01,WT02,WT03,WT04,WT05,WT06,WT07,WT08,WT09,WT11,WT13,WT14,WT15,WT16,WT17,WT18,WT19,WT21,WT22,WV01,WV03
DATE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2000-01-01,USW00014742,"BURLINGTON INTERNATIONAL AIRPORT, VT US",4.6,1309.0,1231.0,0.0,NaN,0.0,0.0,-0.6,5.0,-6.7,265.0,190.0,190.0,0.0,11.2,14.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2000-01-02,USW00014742,"BURLINGTON INTERNATIONAL AIRPORT, VT US",2.6,2318.0,2205.0,4.8,NaN,0.0,0.0,3.9,10.6,-3.3,122.0,180.0,190.0,0.0,10.7,13.9,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-03,USW00014742,"BURLINGTON INTERNATIONAL AIRPORT, VT US",4.9,928.0,1037.0,2.8,NaN,18.0,25.0,5.0,12.8,-2.8,194.0,360.0,360.0,0.0,10.7,13.4,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2000-01-04,USW00014742,"BURLINGTON INTERNATIONAL AIRPORT, VT US",5.4,1446.0,1445.0,8.4,NaN,10.0,25.0,5.0,11.7,-2.2,0.0,230.0,230.0,0.0,13.4,17.4,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2000-01-05,USW00014742,"BURLINGTON INTERNATIONAL AIRPORT, VT US",5.5,209.0,208.0,0.0,NaN,0.0,0.0,-3.9,2.8,-10.6,327.0,330.0,320.0,0.0,11.6,14.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [18]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9528 entries, 2000-01-01 to 2026-01-31
Data columns (total 39 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  9528 non-null   str
 1   NAME     9528 non-null   str
 2   AWND     9514 non-null   float64
 3   FMTM     4273 non-null   float64
 4   PGTM     4185 non-null   float64
 5   PRCP     9528 non-null   float64
 6   PSUN     975 non-null    float64
 7   SNOW     9520 non-null   float64
 8   SNWD     9526 non-null   float64
 9   TAVG     6702 non-null   float64
 10  TMAX     9528 non-null   float64
 11  TMIN     9528 non-null   float64
 12  TSUN     3137 non-null   float64
 13  WDF2     9514 non-null   float64
 14  WDF5     9484 non-null   float64
 15  WESD     4018 non-null   float64
 16  WSF2     9514 non-null   float64
 17  WSF5     9484 non-null   float64
 18  WT01     4028 non-null   float64
 19  WT02     481 non-null    float64
 20  WT03     517 non-null    float64
 21  WT04     169 non-null    float64
 22  WT05     439 non-null    float64
 23  WT06     112 non-null    float64
 24  WT07     25 non-null     float64
 25  WT08     1030 non-null   float64
 26  WT09     219 non-null    float64
 27  WT11     11 non-null     float64
 28  WT13     2093 non-null   float64
 29  WT14     217 non-null    float64
 30  WT15     21 non-null     float64
 31  WT16     2262 non-null   float64
 32  WT17     48 non-null     float64
 33  WT18     1196 non-null   float64
 34  WT19     28 non-null     float64
 35  WT21     56 non-null     float64
 36  WT22     204 non-null    float64
 37  WV01     34 non-null     float64
 38  WV03     2 non-null      float64
dtypes: float64(37), str(2)
memory usage: 2.9 MB

## Weather Key Descriptions:
For more info see *NCEI_weather_codes.pdf*

**NOTE**: Data was downloaded in metric form. Units are in mm for distance, Celcius for temperature, and meters per second for speed.

Basic Descriptors:
- **STATION**: Station identification code
- **NAME**: Name of the station (city/airport name)
- **DATE**: Date of the record (YYYY-MM-DD)

Precipitation:
- **PRCP** = Precipitation (mm)
- **SNOW** = Snowfall (mm)
- **SNWD** = Snow depth (mm)

Sunshine:
- **PSUN** = Daily percent of possible sunshine (percent)
- **TSUN** = Daily total sunshine (minutes)

Air Temperature:
- **TAVG** = Average temperature (Celcius)
- **TMAX** = Maximum temperature (Celcius)
- **TMIN** = Minimum temperature  (Celcius)

Water:
- **WESD** = Water equivalent of snow on the ground (mm)

Wind:
- **AWND** = Average daily wind speed (meters per second)
- **FMTM** = Time of fastest mile or 1-minute wind (hours and minutes HHMM)
- **PGTM** = Peak gust time (hours and minutes HHMM)
- **WDF2** = Direction of fastest 2-minute wind (degrees)
- **WDF5** = Direction of fastest 5-minute wind (degrees)
- **WSF2** = Fastest 2-minute wind speed (meters per second)
- **WSF5** = Fastest 5-minute wind speed (meters per second)

Other Weather Types:
- **WT01** = Fog, ice fog, or freezing fog
- **WT02** = Heavy fog or heavy freezing fog
- **WT03** = Thunder
- **WT04** = Ice pellets, sleet, snow pellets, or small hail
- **WT05** = Hail
- **WT06** = Glaze or rime
- **WT07** = Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction
- **WT08** = Smoke or haze
- **WT09** = Blowing or drifting snow
- **WT11** = High or damaging winds
- **WT13** = Mist
- **WT14** = Drizzle
- **WT15** = Freezing drizzle
- **WT16** = Rain
- **WT17** = Freezing rain
- **WT18** = Snow, snow pellets, snow grains, or ice crystals
- **WT19** = Unknown source of precipitation
- **WT21** = Ground fog
- **WT22** = Ice fog or freezing fog

Weather in the Vicinity:
- **WV01** = Fog, ice fog, or freezing fog
- **WV03** = Thunder

In [19]:
descriptions = {
"STATION" : "Station identification code",
"NAME" : "Name of the station (city/airport name)",
"PRCP" : "Precipitation (mm)",
"SNOW" : "Snowfall (mm)",
"SNWD" : "Snow depth (mm)",
"PSUN" : "Daily percent of possible sunshine (percent)",
"TSUN" : "Daily total sunshine (minutes)",
"TAVG" : "Average temperature (Celcius)",
"TMAX" : "Maximum temperature (Celcius)",
"TMIN" : "Minimum temperature  (Celcius)",
"WESD" : "Water equivalent of snow on the ground (mm)",
"AWND" : "Average daily wind speed (meters per second)",
"FMTM" : "Time of fastest mile or 1-minute wind (hours and minutes HHMM)",
"PGTM" : "Peak gust time (hours and minutes HHMM)",
"WDF2" : "Direction of fastest 2-minute wind (degrees)",
"WDF5" : "Direction of fastest 5-minute wind (degrees)",
"WSF2" : "Fastest 2-minute wind speed (meters per second)",
"WSF5" : "Fastest 5-minute wind speed (meters per second)",
"WT01" : "Fog, ice fog, or freezing fog",
"WT02" : "Heavy fog or heavy freezing fog",
"WT03" : "Thunder",
"WT04" : "Ice pellets, sleet, snow pellets, or small hail",
"WT05" : "Hail",
"WT06" : "Glaze or rime",
"WT07" : "Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction",
"WT08" : "Smoke or haze",
"WT09" : "Blowing or drifting snow",
"WT11" : "High or damaging winds",
"WT13" : "Mist",
"WT14" : "Drizzle",
"WT15" : "Freezing drizzle",
"WT16" : "Rain",
"WT17" : "Freezing rain",
"WT18" : "Snow, snow pellets, snow grains, or ice crystals",
"WT19" : "Unknown source of precipitation",
"WT21" : "Ground fog",
"WT22" : "Ice fog or freezing fog",
"WV01" : "Fog, ice fog, or freezing fog",
"WV03" : "Thunder"
}

categories = {
"STATION" : "Metadata",
"NAME" : "Metadata",
"PRCP" : "Precipitation",
"SNOW" : "Precipitation",
"SNWD" : "Precipitation",
"PSUN" : "Sunshine",
"TSUN" : "Sunshine",
"TAVG" : "Air Temperature",
"TMAX" : "Air Temperature",
"TMIN" : "Air Temperature",
"WESD" : "Water",
"AWND" : "Wind",
"FMTM" : "Wind",
"PGTM" : "Wind",
"WDF2" : "Wind",
"WDF5" : "Wind",
"WSF2" : "Wind",
"WSF5" : "Wind",
"WT01" : "Weather",
"WT02" : "Weather",
"WT03" : "Weather",
"WT04" : "Weather",
"WT05" : "Weather",
"WT06" : "Weather",
"WT07" : "Weather",
"WT08" : "Weather",
"WT09" : "Weather",
"WT11" : "Weather",
"WT13" : "Weather",
"WT14" : "Weather",
"WT15" : "Weather",
"WT16" : "Weather",
"WT17" : "Weather",
"WT18" : "Weather",
"WT19" : "Weather",
"WT21" : "Weather",
"WT22" : "Weather",
"WV01" : "Weather in Vicinity",
"WV03" : "Weather in Vicinity"
}

## Sort Columns by Non-Null Values

In [20]:
# Total number of daily observations
observations = len(df)

coverage = pd.DataFrame({
    "non_null_count": df.notna().sum(),
    "non_null_percentage": df.notna().mean()
}).sort_values("non_null_percentage", ascending=False)

coverage["category"] = categories
coverage["description"] = descriptions


coverage

,non_null_count,non_null_percentage,category,description
STATION,9528,1.000000,Metadata,Station identification code
NAME,9528,1.000000,Metadata,Name of the station (city/airport name)
PRCP,9528,1.000000,Precipitation,Precipitation (mm)
TMIN,9528,1.000000,Air Temperature,Minimum temperature (Celcius)
TMAX,9528,1.000000,Air Temperature,Maximum temperature (Celcius)
SNWD,9526,0.999790,Precipitation,Snow depth (mm)
SNOW,9520,0.999160,Precipitation,Snowfall (mm)
WDF2,9514,0.998531,Wind,Direction of fastest 2-minute wind (degrees)
WSF2,9514,0.998531,Wind,Fastest 2-minute wind speed (meters per second)
AWND,9514,0.998531,Wind,Average daily wind speed (meters per second)
WSF5,9484,0.995382,Wind,Fastest 5-minute wind speed (meters per second)
WDF5,9484,0.995382,Wind,Direction of fastest 5-minute wind (degrees)
TAVG,6702,0.703401,Air Temperature,Average temperature (Celcius)
FMTM,4273,0.448468,Wind,Time of fastest mile or 1-minute wind (hours a...
PGTM,4185,0.439232,Wind,Peak gust time (hours and minutes HHMM)
WT01,4028,0.422754,Weather,"Fog, ice fog, or freezing fog"
WESD,4018,0.421704,Water,Water equivalent of snow on the ground (mm)
TSUN,3137,0.329240,Sunshine,Daily total sunshine (minutes)
WT16,2262,0.237406,Weather,Rain
WT13,2093,0.219668,Weather,Mist
WT18,1196,0.125525,Weather,"Snow, snow pellets, snow grains, or ice crystals"
WT08,1030,0.108102,Weather,Smoke or haze
PSUN,975,0.102330,Sunshine,Daily percent of possible sunshine (percent)
WT03,517,0.054261,Weather,Thunder
WT02,481,0.050483,Weather,Heavy fog or heavy freezing fog
WT05,439,0.046075,Weather,Hail
WT09,219,0.022985,Weather,Blowing or drifting snow
WT14,217,0.022775,Weather,Drizzle
WT22,204,0.021411,Weather,Ice fog or freezing fog
WT04,169,0.017737,Weather,"Ice pellets, sleet, snow pellets, or small hail"
WT06,112,0.011755,Weather,Glaze or rime
WT21,56,0.005877,Weather,Ground fog
WT17,48,0.005038,Weather,Freezing rain
WV01,34,0.003568,Weather in Vicinity,"Fog, ice fog, or freezing fog"
WT19,28,0.002939,Weather,Unknown source of precipitation
WT07,25,0.002624,Weather,"Dust, volcanic ash, blowing dust, blowing sand..."
WT15,21,0.002204,Weather,Freezing drizzle
WT11,11,0.001154,Weather,High or damaging winds
WV03,2,0.000210,Weather in Vicinity,Thunder

## Trailing 7-day Average Calculation

For now, we just compute the mean of the previous 7 days (not including the day itself) and ignore null values. We will have to specify how we want to handle null values and gaps in the dataset.

In [23]:
df_numeric = df.drop(columns=["STATION","NAME"])
weekly_avg = df_numeric.shift(1).rolling(window=7, min_periods=1).mean()

In [24]:
weekly_avg.head()

,AWND,FMTM,PGTM,PRCP,PSUN,SNOW,SNWD,TAVG,TMAX,TMIN,TSUN,WDF2,WDF5,WESD,WSF2,WSF5,WT01,WT02,WT03,WT04,WT05,WT06,WT07,WT08,WT09,WT11,WT13,WT14,WT15,WT16,WT17,WT18,WT19,WT21,WT22,WV01,WV03
DATE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2000-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-02,4.600000,1309.000000,1231.0,0.000000,NaN,0.0,0.000000,-0.600000,5.000000,-6.700000,265.000000,190.000000,190.000000,0.0,11.200000,14.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2000-01-03,3.600000,1813.500000,1718.0,2.400000,NaN,0.0,0.000000,1.650000,7.800000,-5.000000,193.500000,185.000000,190.000000,0.0,10.950000,14.100000,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2000-01-04,4.033333,1518.333333,1491.0,2.533333,NaN,6.0,8.333333,2.766667,9.466667,-4.266667,193.666667,243.333333,246.666667,0.0,10.866667,13.866667,1.0,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2000-01-05,4.375000,1500.250000,1479.5,4.000000,NaN,7.0,12.500000,3.325000,10.025000,-3.750000,145.250000,240.000000,242.500000,0.0,11.500000,14.750000,1.0,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN

## Export Averages to CSV

In [25]:
weekly_avg.reset_index().to_csv(output_csv, index=False)